* Courses
** Penetrator Tester
*** Computer Sciense
*** Computer Systems and Assembly Language
*** C and the Posix Environment
*** Computer Operating systems
*** Database
*** Software Engineering
*** Data Communications
*** Capstone Experience
*** Mobile Computing
*** Intrudction to cybersecurity
*** Info Security and Assurance
*** Info Security in System Admin
*** Web Application Security
*** Computer Forensics
*** Cloud Computing
*** Cyber Operations
*** Web development and security
*** Security in Data Protocols
*** Mathematical Criptography
*** Networking
    
**** IP (Internet Protocol) 

   Is a protocol that ensures that a unique identifier (IP) is assigned
   to each device, in this manner, one can refer to that device on a
   network.
   
***** IP Classes

   They are divided by their range of numbers, the first value determines
   the class, the first three classes (A, B and C) can be used for host
   addresses, the latter classes (D and E) are used for especial
   purposes, for example, D for multicast, and E for experimental
   purposes.

   - Class A :: Its first value can go from 0 to 127, with a subnet mask
		of 8. The latter values can go to a limit of 255. For
		example: 0.0.0.0 - 127.255.255.255, its limit.
   - Class B :: Its first value, from 128 to 191, with a subnet mask of
		16, for example: 128.0.0.0 - 192.255.255.255
   - Class C :: Its first value can go from 192 to 233.
   - Class D :: From 244 to 239.
   - Class E :: From 240 to 255.

   The IP addresses from class A, the first value represents the network
   part, and the latter values, represent the host part.

   For Class B, the first two numbers represent the network part, while
   the latter values, the host.

   And for Class C, the first three numbers represent the network part,
   as you can imagine, some normal IP values to see are the ones on a
   local network, such as your internet, it can be for example: 192.168.0
   When the last number represents your device, for example, your PC can
   be '192.168.1.100', while your cellphone is '192.168.1.101'. 

   If you want to connect to your router, which is a normal device with
   an IP, you have to refer to it with, you guess it, his IP, normally
   one would use its browser, refering to: 192.168.1.1 or 192.168.0.1
   which are the most common IPs that routers have.

   The classes are important, since they declare which network are you
   on, and how many devices can be, in order to know if two devices are
   connected to the same network, one has to know the class and verify
   that the numbers are the same, that way, if device1 has an IP of
   10.0.0.1 and device2 has an IP of 11.0.0.2, they are not on the same
   network.

   Some Special IP address ranges that can be referred if needed are:

   - 0.0.0.0/8 :: addresses used to communicate with the local network

   - 127.0.0.0/8 :: loopback addresses

   - 169.254.0.0/16 :: link-local addresses (APIPA)

**** Subnet Mask

     An IP address has two components, the network address and the host
     address. A subnet mask separates the IP address into the network and
     host addresses. Subnetting further divides the host part of an IP
     address into a subnet and host address. If additional subnetwork is
     needed.

     It is called subnet mask because it is used to identify network
     address of an IP address by performing a bitwise AND operation on the netmask.

     A subnet Mask is a 32-bit number that masks an IP address, and divides
     the IP address into a network address and host address. Subnet Mask is
     made y setting network bits to all "1"s and stting host bits to all
     "0"s.

     Withing a given network, two host addresses are reserved for special
     purpose, and cannot be assigned to hosts. The "0" address is assigned
     a network address and "255" is assigned to broadcast address, and they
     cannot be assigned to hosts.

     Examples of commonly used netmasks for classed networks are 8-bits
     (Class A), 16-bits (Class B) and 24-bits (Class C), and classless
     networks can be found here: [[https://www.iplocation.net/subnet-mask][SubnetMask Classes.]]

     Subnetting an IP network is to separate a big network into smaller
     multiple networks for reorganization and security purposes. All nodes
     (hosts) in a subnetwork see all packets transmitted by any node in a
     network. Performance of a network is adversely affected under heavy
     traffic load due to collisions and retransmissions.

     Aplying a subnet mask to an IP address separates network address from
     host address. The network bits are represented by the 1's in the mask,
     and the host bits are represented by 0's. Performing a bitwise logical
     AND operation on the IP address with the subnet mask produces the
     network address. For example, aplying the class C subnet mask to our
     IP address 216.3.128.12 produces the followind network address: 

     IP:   1101 1000 . 0000 0011 . 1000 0000 . 0000 1100  (216.003.128.012)

     Mask: 1111 1111 . 1111 1111 . 1111 1111 . 0000 0000  (255.255.255.000)

      ---------------------------------------------

      1101 1000 . 0000 0011 . 1000 0000 . 0000 0000  (216.003.128.000)


      Subnetting Network

      Here is another scenario where subnetting is needed. Pretend that a web
      host with a Class C network needs to divide the network so that parts
      of the network can be leased to its customers. Let's assume that a
      host has a network adress of 216.3.128.0 (as shown in the example
      above). Let's say that we're going to divide the network into 2 and
      dedicate the first half to itseld, and the other half to its
      customers.

      216 .   3 . 128 . (0000 0000)  (1st half assigned to the web host)

      216 .   3 . 128 . (1000 0000)  (2nd half assigned to the customers)

      The web host will have the subnet masks of 216.3.128.128 (/25). Now,
      we'll further divide the 2nd half into eight block of 16 IP addresses.
      
      
      
      216 .   3 . 128 . (1000 0000)  Customer 1 -- Gets 16 IPs (14 usable)
      
      216 .   3 . 128 . (1001 0000)  Customer 2 -- Gets 16 IPs (14 usable)
      
      216 .   3 . 128 . (1010 0000)  Customer 3 -- Gets 16 IPs (14 usable)
      
      216 .   3 . 128 . (1011 0000)  Customer 4 -- Gets 16 IPs (14 usable)
      
      216 .   3 . 128 . (1100 0000)  Customer 5 -- Gets 16 IPs (14 usable)
      
      216 .   3 . 128 . (1101 0000)  Customer 6 -- Gets 16 IPs (14 usable)
      
      216 .   3 . 128 . (1110 0000)  Customer 7 -- Gets 16 IPs (14 usable)
      
      216 .   3 . 128 . (1111 0000)  Customer 8 -- Gets 16 IPs (14 usable)
      
      -----------------------------
      
      255 . 255 . 255 . (1111 0000)  (Subnet mask of 255.255.255.240)
      
      CIDR - Classless Inter Domain Routing
  
      Classless InterDomain Routing (CIDR) was invented to keep the internet
      from running out of IP addresses. The IPv4, a 32-bit, addresses have a
      limit of 4,294,967,296(2^32) unique IP addresses. The classfull
      address scheme (Class A, B and C) of allocating IP addresses in 8-bit
      increments can be very wasteful. With classfull addressing scheme, a
      minimun number of IP addresses allocated to an organization is 256
      (Class C). Giving 256 IP addresses to an organization only requiring
      15 IP addresses is wasteful. Also, an organization requitring more
      that 256 IP addresses (let's say 1000 IP addresses) is assigned a
      Class B, which allocates 64,536 IP addresses. Similarly, an
      organization requitring more than 65,636 (65,634 usable IPs) is
      assigned a Class A network, which allocates 16,777,216 (16.7 Million)
      IP addresses. This type of address allocation is very wasteful.
      
      With CIDR, a network of IP addresses is allocated in 1-bit increments
      as opposed to 8-bits in classful network. The use of a CIDR notated
      address can easily represent classful addresses (Class A = /8, Class B
      = /16 and Class C = /24). The number next to the slash (i.e. /8)
      represents the number of bits assigned to the network address. The
      example shown above can be illustrated with CIDR as follows:
      
      
      216.3.128.12, with subnet mask of 255.255.255.128 is written as
      
      216.3.128.12/25
      
      
      
      Similarly, the 8 customers with the block of 16 IP addresses can be
      
      written as:
      
      
      
      216.3.128.129/28, 216.3.128.130/28, and etc.
      
      With an introduction of CIDR addressing scheme, IP addresses are more
      efficiently allocated to ISPs and customers: and hence there is less
      risk of IP addresses running out anytime soon. For detailed
      specification on CIDR, please review RFC 1519. With introduction of
      additional gaming, medical, applicance and telecom devices requiring
      static IP addresses in addition to more that 6.5 billion (july 2006
      est.) world population, the IPv4 addresses with CIDR addressing scheme
      will eventually run out. To solve shortage of IPv4 addresses, the IPv6
      (128-bit) address scheme was introduced in 1993.
      
**** SNMP

     The simple network management protocol is important to the succesful operation
     of your network. If an attacker can breach the SNMP, they may be able to unmask
     your encrypted VPN communication, as well as see and possible control every
     device connected to your network.
     
     Simple Network Management Protocol uses UDP ports 161 and 162 to manage network
     devices. Network devices use this protocol to communicate to each other and
     can be used by administrators to manage the devices. If someone can access the
     SNMP protocol, we can harvest a vast resource of information on the target's
     network and even disable and change the settings on these devices.
     
     The SImple Network Management PRotocol (SNMP) is part of the Internet Protocol
     Suite that is designed to manage computers and network evices. *Cisco* Describes
     it as "and application layer protocol that facilitates the exchange of
     information between network devices". Succint and correct, but it misses the
     management function that SNMP also provides.
     
     SNMP is a stateless, datagram oriented protocol. It involves one or more
     administrative computers called managers. These managers monitor and manage a
     group of computers. Each of the manager computers has an agent installed that
     communicates with the amanager. 
     
     The agent on the managed computers provide management data to the managing
     computer. The manager can undertake management tasks, including modifying and
     aplying new configurations.

**** Internet Protocol Suite
     
     "The internet Protocol Suite is the conceptual model and set of communication
     protocols used in the Internet and similar computer networks."
     
     "A conceptal model in the fiel of computer science is a special case of general
     conceptual model. To distinguix from other rypes of models, it is also known as
     a domain model. Conceptual modeling should not be confused with other modeling
     disciplines such as data modelling, logical modelling and physical modelling.
     The conceptual model is explicitly chosen to be independent of design or
     implementation concerns, for example, concurrency or data storage. The aim of a
     conceptual model is to discuss the problem, and to fin the correct relationships
     between different concepts. The conceptual model attempts to clarify the meaning
     of various, usually ambiguos terms, and ensure that problems with different
     interpretations of the term and concepts cannot occur."
     
     A protocol is a set of rules that one needs to follow in order to
     share information throught the internet, or any other connection. 
     
     "It is usually known as TCP/IP because the foundational protocols in
     the suite are the Transmission Control Protocol (TCP) and the Internet
     Procotol (IP)"
     
***** Transmission Control Protocol
      
      " THe Transmission Control Protocol (TCP) is one of the main protocols
      of the internet protocol suite. It is originated in the initial
      network implementation in which it complemented the Internet Protocol
      (IP). Therefore, the entire suite is commonly referred to as
      TCP/IP. TCP provides reliable, ordered and error-checked delivery of a
      stream of octets (bytes) between applications running on host
      communicating via an IP network. Major internet applications such as
      the World Wide Web, email, remote administrations and file transfer
      rely on TCP. Applications that do not require reliable data stream
      service may use the User Datagram Protocol (UDP), which provides a
      connectionless datagram service that emphasizes reduced latency over
      reliability.

***** UDP

In computer networking, the User Datagram Protocol (UDP) is one of the
core members of the Internet Protocol Suite. With UDP, computer
applications can send messages, in this case referred to as datagrams,
to other hosts on an Internet Protocol (IP) network. Prior
communications are not requiered in order to set up communication
channels or data paths.

UDP uses a simple connectionless communication model with a minimun of
protocol mechanisms. UDP provices checksums for data integrity, and
port numbers for addressing different functions at the source and
destination of the datagram. It gas no handshaking dialogues, and thus
exposes the user's program to any unreliability of the underlying
network; there is no guarantee of delivery, ordering, or duplicate
protection. If error-correction facilitates are needed at the network
interface level, an application may use Transmission Control Protocol
(TCP) or Steam Control Transmission Protocol (SCTP) which are designed
for this purpose.

UDP is suitable for purposes where error checking and correction are
either not necessary or are performed in the application; UDP avoid
the overgead of such processing or are performed in the application;
UDP avoid the overhead of such processing in the protocol
stack. Time-sensitive applications often use UDP because dropping
packets is preferable to waiting for packets delayed due to
retransmission, which may not be an option in a real-time system.

***** Stream Control Transmission Protocol
      
      The Stream Control Transmission Protocol (SCTP) is a computer
      networking communications protocol which operates at the transport
      layer and serves a role similar to the popular protocols TCP and UDP.
      
      SCTP provdes some of the features of both UDP and TCP: it is
      message-oriented like UDP and ensures reliable, in sequence transport
      of messages with congestion control like TCP. It differs from those
      protocols by providing multi-homing and redundant paths to increase
      resilience and reliability.
      
      In the absence of native SCTP support in operating systems, it is
      possible to tunnel SCTP over UDP, as well as to map TCP API calls to
      SCTP calls so existing applications can use SCTP without
      modification. 

***** Internet Protocol
      
      The Internet Procotol (IP) is the principal communications protocol in
      the Internet Procotol Suite for relaying datagrams across network
      boundaries. Its routing function enables internetwroking, and
      essentially establishes the Internet.
      
      Ip has the task of delivering packets from the source host to the
      destination host solely based on the IP addresses in the packet
      headers. For this purpose, IP defines packet structures that
      encapsulate the data to be delivered. It also defines addressing
      methods that are used to label the datagram with source and destination
      information.
      
      IP was the connectionless datagram service in the original
      Transmission Control Program. Which was complemented with a
      connection-oriented service that became the basis for the Transmission
      Control Protocol (TCP). The internet protocol suite is therefore often
      referred to as TCP/IP.
      
      The first major version of IP, IPv4 is the dominant protocol of the
      internet. Its successor, Internet Procotol Version 4 (IPv6) has been
      growind in adoption, reaching almost 25% of all internet traffic.
      
      The internet protocol suite provides *end-to-end data communication*
      specifying how data should be packetized, addressed, transmitted,
      routed and received. This functionality is organized into four
      abstraction layers, which classify all related protocols according to
      the scope of networking involved. From lowest to highest, the layers
      are the link layer, containing communication methos for data that
      remains within a single network segment (link); the internet layer,
      providing internetet working between independent networks; the transport
      layer, handling host-to-host communication; and the application layer,
      providing process-to-process data exchange for applications.
      
      The technical standars underlying the Internet Protocol Suite and its
      constituent protocols are maintained by the Internet Engineering Task
      Force. The Internet Protocol Suite predates the OSI model, a more
      comprehensive reference framework for general networking systems.
      
      Initially, the TCP managed both datagram transmissions and routing,
      but as the protocol grew, other researchers recommended a division of
      functionality into protocol layers. The Transmission Control Program
      was split into two distict protocols, The Transmission Control
      Protocol and the Internet Procotol.
      
      The design of the network included the recognition that it should
      provide only the functions of efficiently transmitting and routing
      traffic between end nodes an that all other intelligente should be
      located at the edge of the network, in the end nodes. This design is
      known as the end-to-end principle. 
      
      A computer called a router is provided with an interface to each
      network. It forwards network packets back and forth between
      them. Originally a router was called gateway, but the term was changed
      to avoid confusion with other types of gateways.

****** Key architectural princniples

       The end-to-end principle has evolver over time. Its original
       expression ut the maintenance of state and overall intelligence at the
       edges, and assumed the Internet that connected the edges retained no
       state and conectrated on speed and simplicity. Real-world needs for
       firewalls, network address translators, web content caches and the
       like have forced changes in this principle. 
       
       The robustness principle states: "In general, and implementation must
       be conservative in its sending behavior, and liberal in its receiving
       behavior. That is, it must be careful to send well-formed datagrams,
       but must accept any datagram that it can interpret (e.g., not object
       to technical errors where the meaning is still clear)." "The second
       part of the principle is almost as important: software on other hosts
       may contain deficiencies that make it unwise to exploit legal but
       obscure protocol features."
       
       Encapsulation is used to provice abstraction of protocols and
       services. Encapsulation is usually aligned with the division of the
       protocol suite into layers of general functionality. In general, and
       pplications (the highest level of the model) uses a set of protocols
       to send its data down to layers. The data is further encapsulated at
       each level.
       
- The application layer is the scope within which applications, or
  processes, create user data and communicate this data to other
  applications on another or the same host. The applications make use
  of the services provided by the underlying lower layers, especially
  the transport layer which provides reliable or unreliable pipes to
  other processes. The communication partners are characterized by the
  application architecture, such as the client-server model and
  peer-to-peer networking. This is the layer in which all applications
  protocols, such as SMTP, FTP, SSH, HTTP, operate. Processes are
  addressed via ports which essentially represent services.
 
- The transport layer performs host-to-host communications on either the
 local network or reomte networks separated by routers. It provides a
 channel for the communications needs of applications. UDP is the basic
 transport layer protocol, providing an unrealiable connectionless
 datagram service. The Transmission Control Protocol provices
 flow-control, connection establishment, and reliable transmission of
 data.
 
- The Internet Layer exchanges datagrams across netowkr boundaries. It
  provides a uniform networking interfaces that hides the actual
  topology (layout) of the underlying network connections. It is
  therefore also the layer that establishes internetworking. Indeed,
  it defines and establishes the Internet. This layer defines the
  addressing and routing structures used for the TCP/IP protocol
  suite. The primary protocol in this crope is the Internet Procotol,
  which defines IP addresses. Its fuction in routing is to transport
  datagrams to the next host, functioning as an IP router, that has
  the connectivity to network closer to the final data destination.
  
- The link Layer defines the networking methods within the scope of
  the local network link hich hosts communicate without intervening
  routiers. This layer includes the protocols used to describe the
  local network topology and the interfaces needed to affect
  transmission of Internet layer datagrams to next-neighbor hosts.

****** Link Layer
       
       The link layer has the networking scope of the local network
       connection to which a host is attached. This regime is called the link
       in TCP/IP literature. It is the lowest component layer of the Internet
       Protocols, as TCP/IP is designed to be hardware independent. As a
       result, TCP/IP may be implemented on top of virtually any hardware
       networking netchnology.
       
       The link layer is used to move packets between the Internet layer
       interfaces of two different hosts on the same link. The processes of
       transmitting and receiving packets on a given link can be controlled
       both in the software device driver for the network card, as well as on
       firmware or specialized chipsets. These perform data link dfunctions
       such as adding a packet header to prepare it for transmission, then
       actually transmit the frane over a physical medium. The TCP/IP model
       includes specifications of translating the network addressing methods
       used in the Internet Protocol to link layer addresses, such as media
       access control (MAC) addressess. All other aspects below that level,
       however, are implicitly assumed to exist in the link layer, but are
       not explicitly defined in the TCP/IP model.
       
       The link layer is also the layer where packets may be selected to be
       sent over a virtual private network or over other
       networkingtunnels. In this scenario, the link layer data may be
       considered application data which traverses another instantiation of
       the IP stack for transmission or reception over another IP
       connection. Such a connection, or virtual link, may be established
       with a transport protocol or even an application scope protocol that
       serves as a tunnel in the link layer of the protocol stack. This, the
       TCP/IP model does not dictate a strict hierarchical encapsulation
       sequence.
       
       The link layer in the TCP/Ip model has corresponding functions in
       Layer 2 o the Open Systems Interconnection (OSI) model.
       
****** Internet Layer
       
       The internet layer has the responsibility of sending packets across
       potentially multiple networks. Internetworking requires sending data
       from the source network to the destination network. This process is
       called routing.
       
       The Internet Protocol performs two basic functions: 
       
- Host addressing and identification :: this is accomplished with a
     hierarchical IP addressing system.
- Packet routing :: This is the basic task of sending packets of data
                    (datagrams) from source to destination by
                    forwarding them to the next network router closer
                    to the final destination.
		    
*** Social Engineering
*** Kali Linux Fundamentals
*** NMAP
*** How to use hping3 (BSWJ)
*** How to use Unicornscan (BSWR)
*** How to use Automater (BSWJ)
*** Malware Fundamentals
*** Malware Threats
*** Phising
*** Red Team Guide
*** USB Drop Attack
*** Penetration Testing and Ethical Hacking
*** Pentest Fundamentals: Scanning Networks
*** Password Cracking Tools Fundamentals
*** How to use THC-Hydra (BSWR)
*** Pentest Fundamentals: Sniffing
*** OWASP
*** Web Application Penetration Testing
*** Intro to Burp Suite Pro
*** SQL Injection
*** Advanced Penetration Testing
*** How to use Armitage - Overview (BSWJ)
*** How to use Armitage - Host Management (BSWJ)
*** How to use Armitage - Exploitation (BSWJ)
*** How to use ExploitDB (BSWJ)
*** Intro to Python
*** Post Exploitation Hacking
*** LABS
**** Certified Ethical Hacker (CEH)
**** Phishing
**** Network Discovery
**** Open Source COllection
**** Premilitary Scanning
**** Additional Scanning Options 
**** Scanning and aMapping Networks
**** Open Source Password Cracking
**** Wireshark
**** Identifying System Vulnerabilities with OpenVAS
**** SQL Injection
**** XSS Reflecete
**** XSS Stored 
**** Unrestricted File Upload
**** Use a Password Cracking Utility in Linux
**** Use Tcpdump to Intercept Network Traffic
**** Obtain Root Credentials in Linux
**** Create a Basic Script in Windows PowerShell
*** Penetration Tester Roles and Responsibilities

 Penetration testers seek to identify security vulnerabilities in an
 organization's networks, and then resolve them, sometimes creating new
 or improved security protocols. This involves many responsibilities
 and tasks.

 As a penetration tester, you will likely be requited to:

 - Perform Penetration test on computer systems, networks, and
   applications
 - Create new testing methods to identify vulnerabilities
 - Perform physical security assessments of systems, servers, and other
   network devices to identify areas that require physical protection
 - Pinpoint methods and entry points that attackers may use to exploit
   vulnerabilities or weaknesses
 - Seach for weaknesses in common software, web applications, and
   propietary systems
 - Research, evaluate, document, and discuss findings with IT teams and management
 - Review and provide feedback for information security fixes
 - Establish Improvements for existing security services, including
   hardware, software, policies and procedures.
 - Identify areas where improvement is needed in security education and
   awareness for users
 - Be sensitive to corporate considerations when performing testing
   (minimize downtime and loss of employee productivity)
 - Stay updated on the latest malware and security threats.

 While the above are typical responsibiliities for a penetrations
 testr, you may have some additional duties depending on the
 organization you work for. Sometimes there is overlap in IT positions,
 so it is important to be flexible and to work as a part of a cohesive
 team.

 ¿What are some penetration Tester Job requirements?

 While it may be possible to fin a job as a penetration tester based
 solely on having the right set of skills, most employers prefer to
 hire penetration testers who have previous relevant work
 experience. Some employees who have at least a bachelor's degree.

 In addition to education, penetration testers are required to have
 certain skills. They must have excellent computer skills to be able to
 attempt hacking systems. They require solid analytical skills to
 evaluate and analyze the processes involved in resolving existing an
 potential security threats. It0's also important for penetrations
 testers to have proficient communication skills as they will be
 writing reports and working closely with the IT proffesionals and
 departments. Most importantly, penetration testers must have
 exeptional problem-solving skills to be able to determine the best
 course of action when resolving issues and protecting networks from
 potential threats or breaches.

 ¿What is a Typical Penetration Tester Job description?

 As a penetration tester you will be responsible for ensuring that
 computer information systems are protected from hackers. That means
 that your role will include running tests on applications, networks,
 and software. You will attempt to hack in, allowing you to access data
 that should not be accessible to unauthorized individuals. You will be
 responsible for identifying any potential weaknesses in existing
 systems and collaborating with other departments and professionals to
 determine the most effective and efficient way to resolve them. This
 may require adding new or additional security measures and rewriting
 program code.

 Additional duties for a penetration tester includes reviewing any
 security system incidents, documenting threats, and completing
 reports concerning your findings. You may also be asked to design
 improved security protocols and policies.

 Ultimately, you will utilize your knowledge to find ulnerabilities in
 networks, internal systems, and applications. This may include
 automated testing, but may also require manually attempting to breach
 security. It may also incluse creating new tests to identify system
 weaknesses and pinpointing entry points for hackers. When
 vulnerabilities are identifies, you will be responsible for advising
 managers or executives on how to make systems more secure.

 A normal day for a penetration tester may include the following tasks:

 - Plan a specific penetration test
 - Create or select the appropriate testing tools
 - Perform the penetration test on networks, applications, or systems
 - Document methodologies
 - Identify vulnerabilities using the data gathered
 - Review and evaluate findings
 - Establish possible solutions for the weaknesses
 - Provide feedback and recommendations to management or clients.
** Network Engineer
*** Networking Fundamentals for Security Practitioners
*** Wireless Network Fundamentals for Security Practitioners
*** Incident Responde and Advanced Forensics
*** Introductions to Wireshard
*** CompTIA Linux + LX0-103
*** CompTIA Linux + LX0-104
*** CCNP Implementing Cisco IP switched Networks (SWITCH)
*** Applying Filters to TCPDump and Wireshard
*** Parse Files Out of Network Traffic
*** Using Snort and Wireshark to Analyze Traffic
*** Harden Windows Hosts
*** Provision Update Management for On-Premises Systems
*** Use the Sysinternals Suite to review Permissions on a Windows System
*** Configure IPv4 and IPv6 Addressing for Linux
*** Configure Linux Ipv4 Routing
*** Configure IP Routing with Linux on Azure
*** Configure Network Connectiviry for LInux on Azure
*** Use Find and Locate to Search for files in Linux
*** Manage Users in Linux
*** Manage Local User Accounts
*** Configure Standard Permissions in Linux
*** Deploy Ubuntu Linux Virtual Machines in the MIcrosoft Azue
*** Configure a Virtual Network Service Endpoint
*** Configure Linux Firewall ACL Rules
*** Manage Software with YUM in Linux
*** Install and Configure a Linux DNS Server
*** Backup and Restore Files with tar in Linux
*** Use RBAC and Design a Custom Role
*** Manage a Serverless Compute Environment
*** Manage Network Settings
*** Manage a Web App
*** Secure Network Access
*** Configure a Network Security Group in a Virtual Network

¿What are some network engineer roles and responsibilities?

Network Engineers make and maintain network systems that all employees
of the organization will use. This role involves many tasks and
responsibilities that can vary, depending on the specific
organization.

As a network engineer, you will likely be required to:

- Administer and maintain computer networks and related computer areas
  such as hardware, systems software, applications software and configurations.
- Protect the security of hardware, software, and data by
  establishing, coordinating, and implementing network security procedures.
- Perform data backups and disaster recovery operations when necessary.
- Order and replace defective or outdated hardware components when necessary.
- Monitor system performance in order to determine when adjsutments
  are necessary.
- Troubleshoot any software, hardware or other system or network
  issues in order to diagnose and resolve the problem
- Configure, maintain, and monitor email applications and virus
  protection programs.
- Work with network users to solve any systems issues
- Coordinate access and use of computer networks
- Operate master consoles for monitoring performance of computer
  systems and networks.

WHile the aboe are typical responsibilities for a network engineer,
you may have additional duties depending on the organization you work
for.

- A solid understanding of network infrastructure and hardware.
- The ability to implement, administer, maintain and troubleshoot
  network infrastructure devices.
- An undertanding of network infrastructure protocols and application transport.
- The ability to provide detailed information for software and
  hardware upgrades or purchases. The ability to produce detailed
  network diagrams and documentation for the esign and planning of
  network systems.
- Excellent analytical skills that allow for finding flaws or areas
  for improvement in complex network systems.
- Strong attention to detail and organization
- Leadership skill when the position requires the network engineer to
  work with a team of other engineers
- The ability to work well with a team of both upper management and subordinates
- Dependability and flexibility
- Lan and WAN experience, as well as network security experience.
- Initiative to stay up-to-date on the latest technology
- An understanding of the hardware and wiring need of the organization

A typical day for a network engineer can vary widely depending on the
culture and industry of the organizzation. While some network
engineers will work a regular 9-5 workdar, there are others who may be
required to work evenings and weekends or be on call should any
network problems arise. However, there are some daily tasks and
responsibilities that are generally common to most network engineer
positions. Based on those taks, a typical day for an etwork engineer
may include:

- Review any downed devices, trouble tickets, and network monitoring tools
- Diagnose and resolve those network issues and continually monitoring
  ticketing system for new trouble tickets entered throughout the day
- Monitor network performance tools and investigate any issues
- Review and perform scheduled maintenance on network systems, as
  necessary
- Review device configurations to ensure they are correct and up to standars
- Work on any ongoing proects including writing project plans,
  monitoring and documenting the progress of the project,
  communicating with other departments and upper management regarding
  the project
- Administrative tasks like inventory and documentation

While the network engineer position is not a cookie cutter job, and
daily responsibilities and tasks can be very different depending on
the organization, the overall goal is to maintain network systems for
users so that they can work efficiently and productively.
** SOC Analyst
*** Launching your SOC Analyst career
*** Introduction to IT & Cybersecurity
*** Networking Fundamentals
*** CompTIA Security + 
*** CompTIA Security+ 501
*** Introduction to Wireshark
*** Vulnerability Scanner Set-up and Configuration
*** Creating Recommendations Base on Vulnerability Assessments
*** Host Data Integrity Baselining
*** Event Log Collection
*** Log Correlation
*** Log Correlation & Analysis to Identify Potential IOC
*** Log Correlation and Analysis
*** Conduct Log Analysis and Cross Examination for False Positives
*** Log Event Reports
*** Wireshard
*** APlying FIlters to TCPDump and Wireshard

¿What are some SOC analyst Roles and Responsibilities?

In general, the role of the SOC analyst is to plan, monitos, and
implement security measures to protect an organization's computer
systems, networks and data. To do this, SOC analysts must stay
up-to-date on the most current intelligence, including hacker's
practices and tactis, to anticipate and prevent security threats and
breachers.

In addition to the above, as a SOC analyst, you will likely be
required to:

- Provide threat analysis and security logs for security devices
- Analyze and respond to hardware and software weakenesses and vulnerabilities
- Investigate, document, and report ssecurity problems and emerging
  security trends
- Coordinate with other analydt and departments regarding system and
  network security when needed
- Create, implement, and maintain security protocols and contorls,
  including the protection of digital files and data against
  unauthorized access
- Maintain data and monitor security access
- Perform risk analyses, vulnerability testing, and security
  assessments
- Perform security audits, internal an external
- Anticipate threats, incidents and alters to help prevent the
  likelihood of them occurring
- Manage network intrusion detection systems
- Analyze all security breacher to determine the root causes
- Make recommendations of countermeasures and install approved tools
- Coordinate security plans with relevant vendors

¿What are some SOC Analyst Job Requirements?

- Knowledge of all security policies
- Training or educating network users about security protocols
- Administration of network firewalls
- Troubleshooting and problem-solving skills
- Identification of security areas that can be improved, and the
  implementation of solutions to those areas
- Dependability and felixibility, being on-call or available outside
  of regular work hours

Some of the common technical knowledge requirements include: 

- Security information and event management (SIEM)
- SQL
- TCP/IP, computer networking, routing and switching
- C, C++, C#, Java or PHP programming languages
- IDS/IPS, penetration and vulnerability testing
- Firewall and intrusion detection/prevention protocols
- Windows, UNIX and Linux operating systems
- Network protocols and packet analysis tools
- Anti-virus and anti-malware
** CyberSecurty Engineer
*** ISC2 Certified Cloud Security Professional (CCSP)
*** CompTIA CASP
*** CompTIA Cloud +
*** ISC2 CISSP - Archive
*** Risk Management Framework
*** Corporate CyberSecurity Management
*** Project Management Professional (PMP) - PMI
*** CISM
*** Fundamental Vulnerability Management
*** Understand Cloud COmputing
*** Risk Management
*** Security Architecture Fundamentals
*** Enterprise Security Architecture
*** CompTIA Advanced Security Practitioner (CASP)
*** Certified Information Systems Security Professional (CISSP)
*** Deloping SQL Databases
*** Centralized Monitoring
*** Preliminary Scanning
*** Data Backup and Recovery
*** Vulnerability Scan Analysis
*** Advanced Techniques for Malware Recovery
*** Applying filters to TCPDump and Wireshark
*** Create custom Snort Rules
*** Dynamic Malware Analysis Capstone
*** Parse Fuiles Out of Network Traffic
*** IDS Setup
*** Compehensive Threat Response
*** Denial of Service PCAP Analysis
*** Recover from SQL Injection Attack
*** Reover from Web-Based Flashpack Incident
*** Post incident Service Restoration
*** Identify whether High-Risk Systes Were Affected

What are some CyberSecurity Engineer Roles and Responsibilities?

Cybersecurity engineers' primary responsibility is to protect the
coputer systems and networks of an organization from threats and
attacks. To achieve that goal, there many taskts and duties that cyber
security engineers must perform. The following are the most common
functions for which cyber security engineers are responsible:

- Development of a set of security practices and standards
- Creating net, more efficient, ways to resolve current security issues
- Making recommendations to management regarding security enhancements
  and improvements
- Performing penetration testing
- Monitoring systems and networks for intrusions or security breaches
- Conducting network scans to identify weaknesses or vulnerabilities
- Installation of software, including data encryption programs and firewalls
- Intallation or processing of security products and procedures
- Installation of appropiate software to improve notifications of intrusions
- Development of automation scripts to manage and track incidents
- Monitoring systems to identify irregular behavior
- Leading incident response efforts
- Leading investigations into breacher that occut
- Supervising and providing feedback for changes in hardware, software
  and user needs
- Reporting findings and feedback to management
- Planning and implementing information security strategies for an
  organization
- Training or educating network users on information security
- Recommending improvements in technical, legal, and regulatory areas
  as they pertain to information security

    Understanding of cyber security methodologies
    The ability to evaluate system changes for security implications and the knowledge to make recommendations for improvements
    Knowledge of current cyber security trends, as well as the continued research of emerging trends and hacking techniques
    Proficiency in Java, Python Net, C++, bash, and power shell
    Networking experience with the TCP/IP stack (may not be a requirement, but is often preferred)
    Solid understanding of the OSI model and renowned ports and services (may not be a requirement, but is often preferred)
    The ability to work well with others, including collaboration and communication with other departments
    The ability to thrive in a fast-paced environment and to work
  under pressure


    Responding to any network or system security breaches or viruses
    Ensuring that appropriate security controls are consistently in place to protect the organizations digital files and infrastructure
    Planning, implementing, managing, monitoring, and upgrading security measures for the protections of systems, networks, and data
    Various administrative tasks, reporting, and communication with other departments
    Performing penetration testing and identifying system and network vulnerabilities


